apiVersion: apps/v1 
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
      labels:
        app: {{ .Values.serviceName }}
        version: "{{ .Values.imageTag }}"
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      {{- if (.Values.acrSecretName) }} 
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{- end }}
#      affinity:
#        nodeAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 1
#            preference:
#              matchExpressions:
#              - key: computeResources
#                operator: In
#                values:
#                - High
      containers:
      - env:
        - name: KIE_WB_ENV_KIE_CONTEXT_PATH
          value: "business-central"
        - name: KIE_WB_PORT_8080_TCP
          value: {{ .Values.workbenchService }}
        - name: KIE_WB_PORT_8080_TCP_ADDR
          value: {{ .Values.workbenchService }}
        - name: HAPI_API_KEY
          valueFrom:
           secretKeyRef:
            name: hapi-fhir-secrets
            key: hapiApiKey
        - name: TRUSTSTORE_PASSWORD
          valueFrom:
           secretKeyRef:
            name: {{ .Values.serviceName }}-secrets
            key: truststorePassword
        - name: KEY_PASSWORD
          valueFrom:
           secretKeyRef:
            name: {{ .Values.serviceName }}-secrets
            key: keyPassword
        {{- if (.Values.dnsEntry) }} 
        - name: DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        {{- end }}
        {{- if (.Values.externalDnsEntry) }} 
        - name: EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        {{- end }}
        {{- if (.Values.wildflyAdminUser) }} 
        - name: WILDFLY_MANAGEMENT_USER
          value: {{ .Values.wildflyAdminUser }}
        # TODO this should be a secret, or potentially no management user at all
        - name: WILDFLY_MANAGEMENT_PASSWORD
          value: {{ .Values.wildflyAdminPwd }}
        {{- end }}
        - name: WILDFLY_LOG_LEVEL
          value: "{{ .Values.wildflyLogLevel | default "WARN" }}"
        - name: PEGACORN_LOG_CATEGORY
          value: "{{ .Values.pegacornLogCategory | default "net.fhirfactory.pegacorn" }}"
        - name: PEGACORN_LOG_LEVEL
          value: "{{ .Values.pegacornLogLevel | default .Values.wildflyLogLevel | default "WARN" }}"
        - name: AETHER_LOG_CATEGORY
          value: "{{ .Values.aetherLogCategory | default "au.gov.act" }}"
        - name: AETHER_LOG_LEVEL
          value: "{{ .Values.aetherLogLevel | default .Values.wildflyLogLevel | default "WARN" }}"
        - name: JAVAX_NET_DEBUG
          value: "{{ .Values.javaxNetDebug | default "none" }}"
        - name: WILDFLY_ENABLE_DEBUG
          value: "{{ .Values.wildflyEnableDebug | default "no" }}"
        - name: KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_BASE_PORT_INSIDE_POD
          value: "{{ .Values.basePortInsidePod | default .Values.basePort }}"
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_BASE_PORT
          value: "{{ .Values.basePort }}"
        - name: HELM_RELEASE_TIME
          value: "{{ date "20060102-150405" .Release.Time }}"
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: JVM_MAX_HEAP_SIZE
          value: "{{ .Values.jvmMaxHeapSizeMB }}m"
        # Set the minimum memory that will be available on the node to assign to the container to be the jvmMaxHeapSizeMB plus 128 MB 
        # for the native heap and operation system processes associated with running Java
        # See http://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#motivation-for-memory-requests-and-limits
        # and http://www.alibabacloud.com/blog/kubernetes-demystified-restrictions-on-java-application-resources_594108
        resources:
          requests:
            memory: "{{ add 128 .Values.jvmMaxHeapSizeMB }}Mi"
        image: {{ .Values.dockerRepo }}pegacorn-kie-execution-server:{{ .Values.imageTag }}            
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          httpGet:
            path: /health
            port: 9993
            scheme: HTTPS
          initialDelaySeconds: 30
        name: wildfly
        ports:
        - containerPort: {{ add 0 (.Values.basePortInsidePod | default .Values.basePort) }}
          name: https
          protocol: TCP
        {{- if (.Values.wildflyAdminUser) }} 
        - containerPort: 9990
          name: admin
          protocol: TCP
        {{- end }}
        {{- if (.Values.wildflyEnableDebug) and (eq .Values.wildflyEnableDebug "Yes") }} 
        - containerPort: 8787
          name: debug
          protocol: TCP
        {{- end }}
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 9993
            scheme: HTTPS
          initialDelaySeconds: 10
        securityContext:
          privileged: false
        volumeMounts:
        - name: certificates
          mountPath: /var/lib/pegacorn-ssl-certs     
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      volumes:
      - name: certificates
        hostPath:
          path: {{ .Values.hostPathCerts }}
